read_players function decomposition
DGAP-clicker-2020/clicker pull request #17
Opened 2020-12-04 18:14 UTC by FrCln

Вынес чтение данных пользователей из файла в отдельную функцию.

2020-12-04 21:56 UTC, sarseniy requested changes
В принципе изменения функции мне понятны, но стиль что-то хворает) Поправьте пожалуйста, тогда можно будет и принять изменения)

2020-12-04 21:56 UTC, sarseniy commented on .gitignore
> +venv
Ok.

2020-12-04 21:56 UTC, sarseniy commented on code/main.py
> +    players = player.read_players()
Okay

2020-12-04 21:56 UTC, sarseniy commented on code/player.py
> +    players = read_players_from_file()
Ясно

2020-12-04 21:56 UTC, sarseniy commented on code/player.py
> -
А где PEP-8?

2020-12-04 21:56 UTC, sarseniy commented on code/player.py
> +
А это зачем?

2020-12-04 21:56 UTC, sarseniy commented on code/player.py
> -
Верните строчку между методами(

2020-12-04 21:56 UTC, sarseniy commented on code/player.py
> +
Зачем так много строк(((

2020-12-04 21:56 UTC, sarseniy commented on code/player.py
> +    print('This module is not for direct run!')
Добавьте пустую строчку в конце.

2020-12-05 08:03 UTC, merged

2020-12-05 08:06 UTC, sarseniy commented
Ой, что-то пошло не так. Я куда-то не туда нажал, Ваш коммит добавился ко мне в ветку, я его отменил, поработал в своей ветке, а затем вмерджил свою ветку в main. И pull request закрылся(

2020-12-05 08:40 UTC, FrCln commented
Он не просто закрылся, он вмерджился благополучно.

2020-12-05 08:52 UTC, sarseniy commented
Ну он сначала вмерджился, потом я его отменил и стал писать свой код. Т.е. на самом деле там этого кода нет)

2020-12-05 08:53 UTC, sarseniy commented
Его #18 поглотил
![image](https://user-images.githubusercontent.com/70952998/101238318-44945980-3701-11eb-82c2-0db4bef3a023.png)

2020-12-05 08:55 UTC, FrCln commented
Ну в истории-то он остался, при желании можно восстановить, хотя это и немного муторно.